paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la BD
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Producto"
        "500":
          description: Error interno en el servidor
    post:
      summary: Registra un nuevo producto en la base de datos
      tags:
        - Products
      response:
        "200":
          description: El nuevo producto se registró con éxito
        "500":
          description: Error interno en el servidor
components:
  schemas:
    Producto:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerada por MongoDB
        title:
          type: String
          description: Título del producto
        description:
          type: String
          description: Descripción del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Código del producto
        stock:
          type: Number
          description: Stock del producto
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: String
          description: Imágenes del producto
        owner:
          type: String
          description: Creador del producto
      example:
        _id: ObjectId("651b3f2337ca4282f6d0f3a7")
        title: Oppenheimer
        description: Biografia
        price: 75
        code: 1001
        stock: 200
        category: Movies
        thumbnail: https://www.infobae.com/new-resizer/f3NsyqLZU4EFZl9fglNeNQBAwyw=/768x1152/filters:format(webp):quality(85)/cloudfront-us-east-1.images.arcpublishing.com/infobae/H2DVBWCFAZGYDFWWN4TEASWRZI.jpg
        owner: bordyestamp@gmail.com

         